spring:
  application:
    name: consumer-test
  security:
    oauth2:
      client:
        provider:
          publisher:
            token-uri: token-url
        registration:
          publisher:
            authorization-grant-type: client_credentials
            provider: publisher
            client-id: client_id
            client-secret: client_secret
  cloud:
    openfeign:
      okhttp:
        enabled: true
integration:
  rabbitmq:
    new-order-queue: newOrderQueue
    cancel-order-queue: cancelOrderQueue
  publisher:
    url: http://localhost:8082
server:
  port: 8081
retry:
  count: 3
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

